#!/usr/bin/env python
#  -*- mode: python; indent-tabs-mode: nil; -*- coding: UTF8 -*-

"""

CSSParser.py

Copyright 2009 by Marcello Perathoner

Distributable under the GNU General Public License Version 3 or newer.

Open an url and return raw data.

"""

import logging
import re
from six.moves import urllib

import cssutils

from libgutenberg.Logger import debug
from libgutenberg.MediaTypes import mediatypes as mt

from ebookmaker import parsers
from ebookmaker.parsers import ParserBase

RE_ELEMENT = re.compile(r'\[[^\]]*\]|((?:^|\s|\+|>|~|,)[a-z0-9]+)', re.I)

mediatypes = (mt.css, )

""" Flex and Grid layouts; generated by Claude
* The grid track-list grammar (repeat(), minmax(), fit-content(),
  named lines, etc.) is approximated with regular expressions. It
  covers the vast majority of real-world usage but is not a perfect
  transcription of the CSS Grid formal grammar (which isn't regular).
  Tighten or loosen the macros below if you hit edge cases.
* Known limitation: named grid lines written with square brackets,
  e.g. `grid-template-columns: [full-start] 1fr [full-end];`, will
  fail to parse at all -- not just fail validation. This is a
  limitation of cssutils' own CSS tokenizer/parser (it doesn't know
  `[` `]` can appear inside a property value), which sits below the
  profile system and can't be fixed by adding a profile. Everything
  else in this file (line-names macro, etc.) is kept for forward
  compatibility / partial matches and in case you patch the tokenizer
  yourself, but square-bracket named lines won't round-trip through
  stock cssutils today.
"""


_MACROS = {
    # basic tokens (defined locally so this profile doesn't depend on
    # exactly which internal macro names cssutils happens to expose)
    'integer': r'[+-]?\d+',
    'num': r'[+-]?\d*\.?\d+(?:[eE][+-]?\d+)?',
    'length': r'(?:{num}(?:em|ex|px|in|cm|mm|pt|pc|ch|rem|vh|vw|vmin|vmax|q)|0)',
    'percentage': r'{num}%',
    'ident': r'-?[a-zA-Z_][a-zA-Z0-9_-]*',
    'string': r'''(?:"[^"]*"|'[^']*')''',
    'lop': r'(?:{length}|{percentage})',           # <length-percentage>
    'lopa': r'(?:{length}|{percentage}|auto)',     # <length-percentage> | auto
    'positive-integer': r'\d+',
 
    # --- Grid: track sizing ---
    'flex-value': r'{num}fr',
    'inflexible-breadth': r'(?:{length}|{percentage}|min-content|max-content|auto)',
    'track-breadth': r'(?:{length}|{percentage}|min-content|max-content|auto|{flex-value})',
    'track-size': r'(?:{track-breadth}|minmax\(\s*{inflexible-breadth}\s*,\s*{track-breadth}\s*\)|fit-content\(\s*{lop}\s*\))',
    'line-names': r'\[\s*{ident}(?:\s+{ident})*\s*\]',
    'track-repeat': r'repeat\(\s*(?:{integer}|auto-fill|auto-fit)\s*,\s*(?:\s*{line-names}?\s*{track-size}\s*)+\s*{line-names}?\s*\)',
    'track-list': r'(?:\s*{line-names}?\s*(?:{track-size}|{track-repeat})\s*)+\s*{line-names}?',
    'auto-track-list': r'(?:\s*{line-names}?\s*{track-size}\s*)*\s*{line-names}?\s*repeat\(\s*(?:auto-fill|auto-fit)\s*,\s*(?:\s*{line-names}?\s*{track-size}\s*)+\s*{line-names}?\s*\)\s*(?:\s*{line-names}?\s*{track-size}\s*)*\s*{line-names}?',
    'grid-line': r'(?:auto|span\s+(?:{integer}\s+{ident}|{ident}\s+{integer}|{integer}|{ident})|{integer}\s+{ident}|{ident}\s+{integer}|{integer}|{ident})',
 
    # --- Shared box-alignment values (used by both grid and flexbox) ---
    'content-position': r'(?:center|start|end|flex-start|flex-end|left|right)',
    'self-position': r'(?:center|start|end|flex-start|flex-end|self-start|self-end)',
    'overflow-position': r'(?:safe|unsafe)',
    'baseline-position': r'(?:(?:first|last)\s+)?baseline',

   # simplified <color>: named/keyword ident, #hex, rgb()/rgba()/hsl()/hsla()
    'hexcolor': r'\#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})',
    'colorfunc': r'(?:rgb|rgba|hsl|hsla)\([^)]*\)',
    'namedcolor': r'(?:currentColor|transparent|{ident})',
    'color': r'(?:{hexcolor}|{colorfunc}|{namedcolor})',

    # text-shadow: <color>? && <length>{2,3} (offsets/blur, in either order relative to color)
    'shadow-item': r'(?:{color}\s+)?{length}\s+{length}(?:\s+{length})?(?:\s+{color})?',

    # from PG_CSS_PROFILE
    'numeric-figure-values': 'lining-nums|oldstyle-nums',
    'numeric-spacing-values': 'proportional-nums|tabular-nums',
    'numeric-fraction-values': 'diagonal-fractions|stacked-fractions',
    'font-variant-attrs': '{numeric-figure-values}|{numeric-spacing-values}|{numeric-fraction-values}|ordinal|slashed-zero',

}
 
# ---------------------------------------------------------------------------
# CSS Grid Layout Module Level 1
# https://www.w3.org/TR/css-grid-1/
# ---------------------------------------------------------------------------
 
GRID_PROPERTIES = {
    'display': r'(?:grid|inline-grid)',
 
    'grid-template-columns': r'(?:none|subgrid|{track-list}|{auto-track-list})',
    'grid-template-rows': r'(?:none|subgrid|{track-list}|{auto-track-list})',
    'grid-template-areas': r'(?:none|(?:{string}\s*)+)',
    'grid-template': r'(?:none|.+)',  # shorthand: permissive (complex grammar)
    'grid': r'.+',                    # shorthand: permissive (complex grammar)
 
    'grid-auto-columns': r'(?:{track-size}\s*)+',
    'grid-auto-rows': r'(?:{track-size}\s*)+',
    'grid-auto-flow': r'(?:(?:row|column)(?:\s+dense)?|dense)',
 
    'grid-row-start': r'{grid-line}',
    'grid-row-end': r'{grid-line}',
    'grid-column-start': r'{grid-line}',
    'grid-column-end': r'{grid-line}',
    'grid-row': r'{grid-line}(?:\s*/\s*{grid-line})?',
    'grid-column': r'{grid-line}(?:\s*/\s*{grid-line})?',
    'grid-area': r'{grid-line}(?:\s*/\s*{grid-line}){0,3}',
 
    # gap properties (introduced alongside Grid Level 1, later folded
    # into Box Alignment Level 3 -- both spellings are included)
    'grid-row-gap': r'{lop}',
    'grid-column-gap': r'{lop}',
    'grid-gap': r'{lop}(?:\s+{lop})?',
    'row-gap': r'{lop}',
    'column-gap': r'{lop}',
    'gap': r'{lop}(?:\s+{lop})?',
 
    'justify-items': r'(?:normal|stretch|{baseline-position}|{overflow-position}?\s*{self-position}|legacy(?:\s+(?:left|right|center))?)',
    'justify-self': r'(?:auto|normal|stretch|{baseline-position}|{overflow-position}?\s*{self-position})',
}
 
# ---------------------------------------------------------------------------
# CSS Flexible Box Layout Module Level 1
# https://www.w3.org/TR/css-flexbox-1/
# ---------------------------------------------------------------------------
 
FLEXBOX_PROPERTIES = {
    'display': r'(?:flex|inline-flex)',
 
    'flex-direction': r'(?:row|row-reverse|column|column-reverse)',
    'flex-wrap': r'(?:nowrap|wrap|wrap-reverse)',
    'flex-flow': r'(?:(?:row|row-reverse|column|column-reverse)(?:\s+(?:nowrap|wrap|wrap-reverse))?|(?:nowrap|wrap|wrap-reverse)(?:\s+(?:row|row-reverse|column|column-reverse))?)',
 
    'order': r'{integer}',
    'flex-grow': r'{num}',
    'flex-shrink': r'{num}',
    'flex-basis': r'(?:content|{lopa})',
    'flex': r'(?:none|(?:auto|{num})(?:\s+{num})?(?:\s+{lopa})?)',
}
 
# ---------------------------------------------------------------------------
# Shared CSS Box Alignment values used by flex/grid containers and items
# (kept as a separate profile so it isn't tied to grid- or flex-only display)
# ---------------------------------------------------------------------------
 
BOX_ALIGNMENT_PROPERTIES = {
    'align-items': r'(?:normal|stretch|{baseline-position}|{overflow-position}?\s*{self-position})',
    'align-self': r'(?:auto|normal|stretch|{baseline-position}|{overflow-position}?\s*{self-position})',
    'align-content': r'(?:normal|{baseline-position}|{overflow-position}?\s*{content-position}|space-between|space-around|space-evenly|stretch)',
    'justify-content': r'(?:normal|{overflow-position}?\s*{content-position}|space-between|space-around|space-evenly|stretch)',
}
 

PG_CSS_PROFILE = {
        'display': 'grid|inline-grid|flex|inline-flex|block|inline|none',
        'justify-content': 'center',
        'speak': r'auto|never|always',
        'speak-as': 'normal|spell-out|digits|literal-punctuation|no-punctuation',
        'all': 'initial|inherit|unset',

        # added to update css fonts level 3
        'font-variant-numeric': r'normal|{font-variant-attrs}(\s+{font-variant-attrs})*',

        # (partial) update to CSS Cascading and Inheritance Level 3
        'background': 'initial',
        'color': 'initial',
        'font-family': 'initial',
        'font-size': 'initial',
        'font-style': 'initial',
        'font-variant': 'initial|all-small-caps',
        'font-weight': 'initial',
        'font': 'initial',
        'margin-right': 'initial',
        'margin-left': 'initial',
        'margin-top': 'initial',
        'margin-bottom': 'initial',
        'margin': 'initial',
        'padding-top': 'initial',
        'padding-right': 'initial',
        'padding-bottom': 'initial',
        'padding-left': 'initial',
        'padding': 'initial',
        'text-align': 'initial',
        'text-indent': 'initial',
        'text-transform': 'initial',

        # updated for  https://www.w3.org/TR/css-writing-modes-3/
        # direction and unicode-bidi  are not supported based on the standard's recommendation
        'writing-mode': 'vertical-lr|vertical-rl|horizontal-tb',
        'text-orientation': 'mixed|upright|sideways',
        'text-combine-upright': 'none | all',      

        # add css3 decoration properties
        'text-decoration-line': r'none|underline|overline|line-through',
        'text-decoration-style': r'solid|double|dotted|dashed|wavy',
        'text-decoration-color': r'{color}',
        'text-decoration': r'(?:none|(?:(?:underline|overline|line-through|blink)(?:\s+(?:underline|overline|line-through|blink)){0,3}|solid|double|dotted|dashed|wavy|{color})(?:\s+(?:(?:underline|overline|line-through|blink)(?:\s+(?:underline|overline|line-through|blink)){0,3}|solid|double|dotted|dashed|wavy|{color})){0,2})',

        # shorthand: <text-emphasis-style> || <text-emphasis-color>
        'text-emphasis': r'(?:none|(?:{string}|(?:filled|open)(?:\s+(?:dot|circle|double-circle|triangle|sesame))?|(?:dot|circle|double-circle|triangle|sesame)(?:\s+(?:filled|open))?|{color})(?:\s+(?:{string}|(?:filled|open)(?:\s+(?:dot|circle|double-circle|triangle|sesame))?|(?:dot|circle|double-circle|triangle|sesame)(?:\s+(?:filled|open))?|{color}))?)',
        'text-emphasis-style': r'(?:none|{string}|(?:filled|open)(?:\s+(?:dot|circle|double-circle|triangle|sesame))?|(?:dot|circle|double-circle|triangle|sesame)(?:\s+(?:filled|open))?)',
        'text-emphasis-color': r'{color}',

        # text-underline-position: auto | [ under || [ left | right ] ]
        'text-underline-position': r'(?:auto|under(?:\s+(?:left|right))?|(?:left|right)(?:\s+under)?)',

        # text-emphasis-position: [ over | under ] && [ right | left ]
        'text-emphasis-position': r'(?:(?:over|under)\s+(?:right|left)|(?:right|left)\s+(?:over|under))',

        # text-shadow: none | <shadow>#
        'text-shadow': r'(?:none|{shadow-item}(?:\s*,\s*{shadow-item})*)',
 
        # initial letter for accessible drop caps
        # <number> = the sink's size, in number of lines; the optional
        # <integer> = the sink, how many lines it descends (defaults to
        # round(<number>) when omitted)
        'initial-letter': r'(?:normal|{num}(?:\s+{integer})?)',

        # initial-letter-align: [ auto | alphabetic | hanging | ideographic ]
        'initial-letter-align': r'(?:auto|alphabetic|hanging|ideographic)',
    
        # initial-letter-wrap: none | first | all | grid | <length-percentage>
        'initial-letter-wrap': r'(?:none|first|all|grid|{lop})',

        'background-size': (r'^(?:cover|contain|(?:auto|{length}|{percentage})(?:\s+(?:auto|{length}|{percentage}))?)(?:\s*,\s*(?:cover|contain|(?:auto|{length}|{percentage})(?:\s+(?:auto|{length}|{percentage}))?))*$'
        )
}
        
# ---------------------------------------------------------------------------
# Register the profiles with cssutils
# ---------------------------------------------------------------------------
 
cssutils.profile.addProfile('CSS Grid Layout Module Level 1', GRID_PROPERTIES, _MACROS)
cssutils.profile.addProfile('CSS Flexible Box Layout Module Level 1', FLEXBOX_PROPERTIES, _MACROS)
cssutils.profile.addProfile('CSS Box Alignment (Flexbox/Grid)', BOX_ALIGNMENT_PROPERTIES, _MACROS)
cssutils.profile.addProfile('Added Properties for Project Gutenberg', PG_CSS_PROFILE, _MACROS)

class Parser(ParserBase):
    """ Parse an external CSS file. """

    def __init__(self, attribs=None):
        cssutils.log.setLog(logging.getLogger('cssutils'))
        # logging.DEBUG is way too verbose
        cssutils.log.setLevel(max(cssutils.log.getEffectiveLevel(), logging.INFO))
        ParserBase.__init__(self, attribs)
        self.sheet = None

    def pre_parse(self):
        """ Parse the CSS file. """

        if self.sheet is not None:
            return

        parser = cssutils.CSSParser()
        if self.fp:
            self.sheet = parser.parseString(self.unicode_content())
        else:
            try:
                self.sheet = parser.parseUrl(self.attribs.url)
            except ValueError:
                logging.error('Missing file: %s', self.attribs.url)
                return

        self.attribs.mediatype = 'text/css'
        self.lowercase_selectors(self.sheet)
        self.make_links_absolute()


    def parse_string(self, s):
        """ Parse the CSS in string. """

        if self.sheet is not None:
            return

        parser = cssutils.CSSParser()
        self.sheet = parser.parseString(s)

        self.attribs.mediatype = 'text/css'
        self.lowercase_selectors(self.sheet)


    @staticmethod
    def iter_properties(sheet):
        """ Iterate on properties in css. """
        for rule in sheet:
            if rule.type == rule.STYLE_RULE:
                for prop in rule.style:
                    yield prop


    @staticmethod
    def lowercase_selectors(sheet):
        """ make element names in selectors lowercase to match xhtml tags """
        for rule in sheet:
            if rule.type == rule.STYLE_RULE:
                for sel in rule.selectorList:
                    sel.selectorText = RE_ELEMENT.sub(
                        lambda m: m.group(1).lower() if m.group(1) else m.group(0),
                        sel.selectorText)

    def make_links_absolute(self):
        """ make links absolute """
        def abs_url(url):
            return urllib.parse.urljoin(self.attribs.url, url)
        cssutils.replaceUrls(self.sheet, abs_url)


    def rewrite_links(self, f):
        """ Rewrite all links using the function f. """
        cssutils.replaceUrls(self.sheet, f)


    def iterlinks(self):
        """ Return the urls of all images in document."""

        for url in cssutils.getUrls(self.sheet):
            yield urllib.parse.urljoin(self.attribs.url, url), parsers.em.style()

    def strip_images(self):
        """ remove all rules with url() in them """
        to_delete = []
        for rule in self.sheet:
            if rule.type == rule.STYLE_RULE and rule.cssText and 'url(' in rule.cssText:
                to_delete.append(rule)
        for rule in to_delete:
            self.sheet.deleteRule(rule)


    def get_aux_urls(self):
        """ Return the urls of all auxiliary files in document.

        Auxiliary files are non-document files you need to correctly
        display the document file, eg. CSS files.

        """

        aux = []

        for rule in self.sheet:
            if rule.type == rule.IMPORT_RULE:
                aux.append(urllib.parse.urljoin(self.attribs.url, rule.href))

        return  aux


    def serialize(self):
        """ Serialize CSS. """

        return self.sheet.cssText
