#!/usr/bin/env python
#  -*- mode: python; indent-tabs-mode: nil; -*- coding: UTF8 -*-

"""

ebookmaker script

Copyright 2014 by Marcello Perathoner

Distributable under the GNU General Public License Version 3 or newer.

This script starts epubmaker.

"""

from ebookmaker import EbookMaker

EbookMaker.main ()
